services:
  - type: web
    name: payanam-bus-tracking
    env: docker
    plan: free
    region: oregon
    numInstances: 1
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
